# Generated by Django 2.2 on 2019-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
