# Generated by Django 2.2 on 2019-04-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commnet_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.BooleanField(null=True),
        ),
    ]
